default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: indel
  username: postgres
  password: indel2025
  host: 127.0.0.1
  port: 5432

production: &production
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>

cable:
  <<: *production

queue:
  <<: *production
  migrations_paths: db/queue_migrate
